### ISSUE TITLE
Background/Foreground Service Setup

### ISSUE THREAD

**Issue by rodvar** [bisq-network/bisq-mobile#53]
Currently we have a POC-based example of how to use bisq core to connect to the network and communicate.
We need to structure that into the Android (node) app to provide the most efficient and reliable service possible.

Goals:

1. Apply Koin DI for all bisq services instances which are mostly singletons, and do the proper configuration of them on the koin module so they are ready to be used (this is important for waking up the app and having all ready when clicking on a notification)
2. Develop an [Android Foreground Service](https://developer.android.com/develop/background-work/services/foreground-services) that shows a silent minimalist notification with the apps service state (e.g. "Bisq is <STATE>") and refactor all the current POC 
3. migrate all the p2p functionality coming from the POC to this service
4. test it runs even after killing the app, notification, on click notification to get back to app etc

following this effort each of the features that uses the shared repositories to communicate wiht the rest of the app should be implemented (see P2P Service preffix coming issues)

Things to discuss and decide with team:

 - app should be persistent? (discuss STOP foreground service button)
 - system notification UI (can't use compose, traditional Android Layout XML)
 - lay down the basic abstractions to allow reusal for the xClients.

**Comment by rodvar** [comment]
on further conversations with the team we identified that also the service will be needed in the `xClients`.

The foreground service approach would be definitly useful in the `androidClient` , the only difference is that it would use a different networking client / services. But the whole notification approach, and low-energy consuming availability non-functional requirements are the same. There is no KMP lib to get the best of both worlds with one single shared code, but we can use expect/actual to code everything (or mostly everything) in kotlin and get the right OS components for iosMain and androidMain.

Probably best to use this issue as the foundational brick for all of this.

**Comment by rodvar** [comment]
Reads for the iOS side:

 - [background modes](https://developer.apple.com/documentation/xcode/adding-capabilities-to-your-app#Enabling-Background-Modes)
 - [BG task scheduler](https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler)
 - [local notifications](https://developer.apple.com/documentation/usernotifications/scheduling-a-notification-locally-from-your-app)

**Comment by HenrikJannsen** [comment]
Just some update from my side on the network side.

Websockets:
I got web-sockets working and a PR will come soon. Then polling is not needed anymore and also the rest api http requests will get routed over the WS connection. Thus only one connection to the backend is needed. This is specially important for the Tor use case as creating a new circuit for each rest api request is wasteful and degrades UX (can take a few seconds and sometimes it fails). 

We will proxy the rest api calls on the WS server. It unpacks the message and creates a http request our of it and calls the localhost rest api enpoints. We could also shortcut it to call directly the java api but I think then the rest api endpoints will not get well maintained, and the small overhead is not an issue as we only have one client and its a localhost call.
The WS server can serve additionally the rest api endpoints, so no need to start 2 servers. The config allows to decide how to use it (rest api server only, ws server only, ws+rest api).

Tor:
As for making a rest api node (or desktop with rest api enabled) accessible to the mobile client the user need to do NAT traversial, usually by setting up port forwarding. This is not for non technical users a hurdle and does not work with all routers and sometimes internet providers do not permit access to the router (or you are in a restricted environment like an Air BNB flat or hotel). To run on a VPS is also a hurdle for non technical ppl. So the clearnet option will come with severe accessibility issues.
Tor is solving all those issues and more. It was thought that Tor support on iOS is not feasible (as it was a while ago) but luckily now Orbit is available on iOS as well (on Android since long). 
Orbit is endorsed by Tor project and the devs are closely connected. It is a VPN application which gets special network capabilities by Apple. This entitlement is given very restrictively and it is very unlikely that Bisq would get that from Apple. 
But if the user has Orbit installed we can use the system provided tor which keeps running in background and by that solving most of the problems.
Same for Android (though here we could implement it ourselves as there are no Google side restrictions, though its a bit of an effort and several hacks are applied to keep Tor running in background). 
So the best approach to get Tor support for all apps (node and clients) is to use Orbit and require the user to install it if not already installed.

To re-open the web-socket connection over Tor is not that a big deal if Tor is already running in the background. There might be some tricks to keep at least for a while the WS connection open even the app is in background. But even if it gets closed by the OS, the UX drawback is manageable IMO. E.g. when going back into foreground you get a re-connect screen for 1-3 seconds. 

I will write a more detailed discussion post about all that in a few days.

**Comment by rodvar** [comment]
the base foundation for this is done with the merge PR

**Comment by rodvar** [comment]
We can close this one for now since

 - solution uses foreground service whenever possible on android otherwise background & background for iOS
 - iOS bug issue has been created #94 
 - https://github.com/bisq-network/bisq-mobile/issues/126 has been created as a follow up
